### ISSUE TITLE
Some feedback for improvements

### ISSUE THREAD

**Issue by AnonGO** [hardba11/bourrasque#88]
The cockpit model is amazing but it needs some minor improvements, i understand that this is classified still but some flight model can be altered as well as the effect turning has on speed etc etc and last but not least is to put a functional master arm as well as missiles and a gattling gun. I say again i can understand the difficulties because it is still classified but some changes might be made.

Thank you in advance and im looking forward to hear you update this masterpiece of an aircraft that you made!!

**Comment by hardba11** [comment]
Hello,

here are some clarifications :
- I will make only minor improvment on cockpit because I planned to create a totally new one as beautiful as the m2000-5's one ;)  (as soon as I have time).
- It's fictive cockpit so nothing is classified.
- the flight model used to be altered  according to the mod (choice among 4 mods : TAXI, APP, NAV, VFR). It is this is no longer the case since the fdm has been entirely refactored to avoid nasal overhead.
- there are no weapons on brsq

Could you be more specific about your request ?

Regards

**Comment by AnonGO** [comment]
Hello,

the flight model needs some improvement in terms of the flaps that are not retractable (unless its automatic) secondly it doesnt bleed airspeed easily meaning if you try a split S manoeuvre with 450 knots the plane wont lose any airspeed meaning it would plunder to the ground.

Regards
